// Generated by Takahe v0.1.1
// Target: ttl7400

module parts (
    input  a,
    input  b,
    output nand_here,
    output nor_here,
    output xor_here,
    output inv_here
);

wire tmp_7;
wire tmp_8;
wire tmp_9;
wire tmp_10;
wire tmp_11;
wire tmp_12;

LS00_NAND2 U0 ( .A(a), .B(b), .Y(tmp_8) );
LS34_BUF U1 ( .A(tmp_8), .Y(nand_here) );
LS02_NOR2 U2 ( .A(a), .B(b), .Y(tmp_10) );
LS34_BUF U3 ( .A(tmp_10), .Y(nor_here) );
LS86_XOR2 U4 ( .A(a), .B(b), .Y(tmp_11) );
LS34_BUF U5 ( .A(tmp_11), .Y(xor_here) );
LS04_INV U6 ( .A(a), .Y(tmp_12) );
LS34_BUF U7 ( .A(tmp_12), .Y(inv_here) );

endmodule
