/* Copyright (c) 2026 Zane Hambly
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/*
 * tk_blif.c -- BLIF netlist emitter for Takahe RTL
 *
 * Berkeley Logic Interchange Format: the Esperanto of
 * synthesis tools. Nobody's first language, but everyone
 * speaks it well enough to get the job done.
 *
 * Emits combinational gates as .names (truth tables),
 * DFFs as .latch, and wires everything up by net name.
 * The output can be fed into ABC, Yosys, or nextpnr.
 *
 * Limitation: no support for multi-bit operations yet.
 * Each cell is emitted as a single-bit BLIF gate with
 * a width annotation in a comment. Downstream tools
 * will need to handle vectorisation themselves.
 */

#include "takahe.h"
#include <inttypes.h>

/* ---- Net name helper ---- */

static const char *
bl_nnam(const rt_mod_t *M, uint32_t ni, char *buf, int bsz)
{
    const rt_net_t *n;
    if (ni == 0 || ni >= M->n_net) {
        snprintf(buf, (size_t)bsz, "$nil");
        return buf;
    }
    n = &M->nets[ni];
    snprintf(buf, (size_t)bsz, "%.*s_%u",
             (int)n->name_len, M->strs + n->name_off, ni);
    return buf;
}

/* ---- Public: emit BLIF to file ---- */

int
mp_blif(const rt_mod_t *M, FILE *fp)
{
    uint32_t i;
    char nb[64], n0[64], n1[64], n2[64];

    if (!M || !fp) return -1;

    fprintf(fp, "# BLIF generated by Takahe\n");
    fprintf(fp, ".model takahe_top\n");

    /* Inputs */
    fprintf(fp, ".inputs");
    for (i = 1; i < M->n_net; i++) {
        if (M->nets[i].is_port == 1)
            fprintf(fp, " %s", bl_nnam(M, i, nb, 64));
    }
    fprintf(fp, "\n");

    /* Outputs */
    fprintf(fp, ".outputs");
    for (i = 1; i < M->n_net; i++) {
        if (M->nets[i].is_port == 2)
            fprintf(fp, " %s", bl_nnam(M, i, nb, 64));
    }
    fprintf(fp, "\n\n");

    /* Cells */
    for (i = 1; i < M->n_cell; i++) {
        const rt_cell_t *c = &M->cells[i];
        if (c->type == RT_CELL_COUNT) continue;

        switch ((int)c->type) {

        case RT_CONST:
            /* .names output  \n  0 or 1 */
            fprintf(fp, "# CONST val=%" PRId64 " w=%u\n",
                    c->param, c->width);
            fprintf(fp, ".names %s\n",
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "%s\n\n", c->param ? "1" : "");
            break;

        case RT_ASSIGN:
            /* .names in out  \n  1 1 */
            fprintf(fp, ".names %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "1 1\n\n");
            break;

        case RT_NOT:
            fprintf(fp, ".names %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "0 1\n\n");
            break;

        case RT_AND:
            fprintf(fp, ".names %s %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->ins[1], n1, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "11 1\n\n");
            break;

        case RT_OR:
            fprintf(fp, ".names %s %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->ins[1], n1, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "1- 1\n-1 1\n\n");
            break;

        case RT_XOR:
            fprintf(fp, ".names %s %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->ins[1], n1, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "10 1\n01 1\n\n");
            break;

        case RT_MUX:
            /* MUX(sel, d0, d1): sel=0→d0, sel=1→d1 */
            fprintf(fp, "# MUX w=%u\n", c->width);
            fprintf(fp, ".names %s %s %s %s\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->ins[1], n1, 64),
                    bl_nnam(M, c->ins[2], n2, 64),
                    bl_nnam(M, c->out, nb, 64));
            fprintf(fp, "0-1 1\n10- 1\n\n");
            break;

        case RT_DFF:
            /* .latch D Q re CLK 0 */
            fprintf(fp, ".latch %s %s re %s 0\n\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->out, nb, 64),
                    bl_nnam(M, c->ins[1], n1, 64));
            break;

        case RT_DFFR:
            /* .latch D Q re CLK 0 (reset as subcircuit) */
            fprintf(fp, "# DFFR (async reset %s)\n",
                    bl_nnam(M, c->ins[2], n2, 64));
            fprintf(fp, ".latch %s %s re %s 0\n\n",
                    bl_nnam(M, c->ins[0], n0, 64),
                    bl_nnam(M, c->out, nb, 64),
                    bl_nnam(M, c->ins[1], n1, 64));
            break;

        default:
            /* Generic: emit as .subckt with type annotation */
            fprintf(fp, "# %s w=%u (no BLIF equiv)\n",
                    rt_cname(c->type), c->width);
            fprintf(fp, ".subckt %s", rt_cname(c->type));
            fprintf(fp, " O=%s", bl_nnam(M, c->out, nb, 64));
            {
                uint8_t j;
                for (j = 0; j < c->n_in; j++) {
                    char ij[8];
                    snprintf(ij, 8, "I%u", (unsigned)j);
                    fprintf(fp, " %s=%s", ij,
                            bl_nnam(M, c->ins[j], n0, 64));
                }
            }
            fprintf(fp, "\n\n");
            break;
        }
    }

    fprintf(fp, ".end\n");
    return 0;
}
